### ISSUE TITLE
Auth support

### ISSUE THREAD

**Issue by hansmbakker** [SvenEV/WinSwag#39]
I added [authorization header support](https://swagger.io/docs/specification/2-0/authentication/api-keys/) using
```
security:
  - APIKeyHeader: []

securityDefinitions:
   # X-API-Key: abcdef12345
   APIKeyHeader:
     type: apiKey
     in: header
     name: X-API-Key
```

but WinSwag does not handle that and therefore I can't test my requests against a server that requires authorization
